[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fabio Caffarello", email = "fabio.caffarello@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/agents"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
